[SDR-273] BE : 가게의 리뷰 목록 조회 API 구현
jjik-muk/sikdorak pull request #173
Opened 2022-09-13 10:04 UTC by jinan159

### ❗️ 이슈 번호

[SDR-273]

<br><br>

### 📝 구현 내용

- 가게의 리뷰 목록 조회 API 구현

2022-09-13 10:59 UTC, ku-kim requested changes
고생 많으셨어요 제이!

2022-09-13 10:59 UTC, ku-kim commented on be/src/docs/asciidoc/store/store.adoc
> +=== 가게 상세 조회`
api 문서는 다음 PR에 싹 바꾸겠습니다 `_'

2022-09-13 10:59 UTC, ku-kim commented on be/src/docs/asciidoc/store/store.adoc
> +operation:store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-body']
":"가 한개라면 작동 안할 거 같네요.! 
머지된이후 제가 수정할게요

2022-09-13 10:59 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreReviewsSearchByStoreIdDocumentationTest.java
> +@DisplayName("문서화 : Store(특정 가게)의 리뷰 리스트 조회")
통일성 good!

2022-09-13 10:59 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
> +            assertThat(reviews).isNotEmpty()
reviews에서 isNotEmpty() 체크하니 assertThat(reviewResponse).isNotNull(); 은 빠져도 괜찮지 않을까요?!

2022-09-13 10:59 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreReviewsSearchByStoreIdDocumentationTest.java
> +			.when()
p3; when, then 개행 통일하면 좋을거같아요

2022-09-13 10:59 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
> +        """)
p1; 쿼리가 public, protected, private 모두 조회될 거 같은데요!?

이야기 나눴던, public만 조회하는건 어떠신가요?

```suggestion
    @Query("""
        SELECT r FROM Review r
         WHERE r.storeId = :storeId
           AND r.reviewVisibility = 'PUBLIC'
           AND r.id <= :targetId
         ORDER BY r.id DESC
        """)
```

2022-09-13 10:59 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
> +                    )
PUBLIC한 리뷰들만 조회된다로, 접근 권한 여부도 테스트파면 좋을거같아요!

2022-09-13 11:44 UTC, jinan159 commented on be/src/docs/asciidoc/store/store.adoc
> +=== 가게 상세 조회`
제가 수정하겠습니다ㅎㅎ;;

2022-09-13 11:45 UTC, jinan159 commented on be/src/docs/asciidoc/store/store.adoc
> +operation:store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-body']
이 부분도 같이 수정할게요

2022-09-13 11:46 UTC, Seokho-Ham submitted a review, later dismissed
고생하셨어요 제이~👍
(이미 쿠킴이 필요한 부분들은 이야기를 하셔서 따로 코멘트는 남기지 않았습니다!)

2022-09-13 11:53 UTC, jinan159 commented on be/src/test/java/com/jjikmuk/sikdorak/documentationtest/store/StoreReviewsSearchByStoreIdDocumentationTest.java
> +			.when()
아.. 이게 제가 IntelliJ 에서 commit 할때 code reformat 하도록 설정되어있어서 그런가보네요;;
해제하고 수정 해놓겠습니다

2022-09-13 12:15 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/review/repository/ReviewRepository.java
> +        """)
추가한다는게 깜빡했네요;; 수정해서 push 했습니다

2022-09-13 12:16 UTC, jinan159 commented on be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
> +                    )
반영완료👍

2022-09-13 12:36 UTC, jinan159 commented on be/src/test/java/com/jjikmuk/sikdorak/integration/review/ReviewsSearchByStoreIdIntegrationTest.java
> +            assertThat(reviews).isNotEmpty()
null 이면 NPE 가 터질테니 그것도 괜찮은 방법이긴 하네요..!
그런데 저는 NPE 터지는걸 잡는거보다 assert 로 잡는것도 괜찮을 거 같습니다 ㅎㅎ

2022-09-14 01:14 UTC, ku-kim approved these changes
고생 넘 많으셨어요 jay!!! 🥹

2022-09-14 02:13 UTC, merged