[SDR-241] BE : 지도에서 위치기반 가게목록 조회 API
jjik-muk/sikdorak pull request #174
Opened 2022-09-13 16:34 UTC by Seokho-Ham

### ❗️ 이슈 번호

[SDR-241]

<br><br>

### 📝 구현 내용

- 위치기반 가게 목록 조회 기능 구현
  - 페이징 사용

<br><br>

### 💡 참고 자료

<img width="450" alt="Screen Shot 2022-09-14 at 1 30 19" src="https://user-images.githubusercontent.com/57708971/189956738-b7ec68d3-bf5e-49ab-b12c-0a35e205b7f3.png">

<img width="750" alt="Screen Shot 2022-09-14 at 1 30 26" src="https://user-images.githubusercontent.com/57708971/189956811-7f98947a-d29e-4402-adb9-d3d6280f48ee.png">

<img width="301" alt="Screen Shot 2022-09-14 at 1 32 50" src="https://user-images.githubusercontent.com/57708971/189957079-38ad5372-d781-4d4c-958c-4b308884cce5.png">

<img width="313" alt="Screen Shot 2022-09-14 at 1 32 03" src="https://user-images.githubusercontent.com/57708971/189956907-dc8057d3-0213-4bce-a7d3-55bc83bfb6c5.png">

2022-09-13 23:37 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/CoordinateUtil.java
> +public class CoordinateUtil {
p2;
`CoordinateUtil` 이 꼭 bean 이 아니어도 되겠다는 생각이 들어요.

2022-09-13 23:41 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/CoordinateUtil.java
> +    }
복잡한 계산식 구현하시느라 고생하셨네요👍
이 계산식의 수식을 주석으로 적어주시거나, 참고한 링크를 주석으로 남겨 주시면 더 좋을 것 같습니다😁

2022-09-13 23:42 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/store/repository/StoreRepository.java
> +        Pageable pageable);
서비스단에서 복잡한 계산을 미리 한 덕분에, 쿼리는 정말 간단해졌네요👍

2022-09-13 23:55 UTC, jinan159 submitted a review, later dismissed
현재 위치기반 검색 구현하신다고 넘 고생많으셨습니다👏👏

2022-09-14 05:53 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/DistanceCalcUtil.java
> +    }
해당 클래스가 생성되지 않도록 하기 위함이군요👍👍

----

p3; 
abstract class, interface 로 선언하면 이 부분을 작성하지 않아도 됩니다!

2022-09-14 05:55 UTC, ku-kim requested changes, later dismissed

2022-09-14 05:55 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/DistanceCalcUtil.java
> +    }
완전 유틸 클래스가 되었군요 👍

p3; 혹시 계산 로직에 대한 주석 추가해주실 수 있나요? 
계산 방법이나 참고 링크 있으면 좋을거같아요!

+a)
거리계산 유틸이라고하는데 isValidDistance()만 사용하고 있는데요
UserLocationBasedMax 와 유사한 거 같은데 특별히 구분한 이유가 있을까요?

2022-09-14 05:55 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/UserLocationInfoRequest.java
> +}
컨트롤러에서 사용자 입력으로 받는 Request인데 테스트는 domain에 포함되어있네요.!

p3; 혹시 UserLocationInfoRequest는 단순히 입력 객체로만 받고,
유효성 검증이나 로직은 UserLocationInfo 란 도메인 객체를 별도로 만들어 관리하는것은 어떠세요?
 
UserLocationInfo 객체 생성은 서비스에서 생성하구요!

2022-09-14 05:55 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
> +		UserLocationBasedMaxRange coordinates = new UserLocationBasedMaxRange(userLocationInfoRequest);
오우 깔끔해졌네요! 의견 받아주셔서 감사합니다.
짱짱 퐄퐄

2022-09-14 05:55 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
> +					radius))
여기서 valid 체크하는 특별한 이유가 있을까요?
DB에서 가져올 때 사각형  범위 데이터만 가져온 것에 더하여 반지름도 검증하는건가요?

2022-09-14 05:55 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/dto/UserLocationBasedMaxRange.java
> +    public UserLocationBasedMaxRange(UserLocationInfoRequest userLocationInfoRequest) {
p3; 도메인이 Request를 알고있어서 꺼내는게 좋을거같아요!

2022-09-14 05:55 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/unittest/store/domain/UserLocationInfoRequestTest.java
> +                        .isInstanceOf(InvalidUserLocationException.class);
p2; 최대, 최소 테스트는 다른 경우라 생각되어서 assertAll()로 묶기 보다는 테스트를 두 번 작성하는게 좋아보여요!
값이 반복된다면 parameterizedtest 적용하면 좋을 거 같습니다!

아래 테스트들도 동일할 거 같아요

2022-09-14 05:59 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/CoordinateUtil.java
> +public class CoordinateUtil {
Bean vs static

https://meansoup.github.io/docs/spring/static-method-vs-bean

2022-09-14 06:03 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/dto/UserLocationBasedMaxRange.java
> +    private static final int EARTH_RADIUS = 3761;
earch radius 와 계산 수식에 대한 설명이 있으면 더 빠르게 이해할 수 있을 것 같습니다🥹
(참고하신 자료 등)

2022-09-14 06:05 UTC, jinan159 submitted a review, later dismissed

2022-09-14 06:09 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/DistanceCalcUtil.java
> +    }
주석으로 링크 추가해두겠습니다!
isValidDistance 메서드는 스토어의 좌표와 사용자의 좌표를 받아서 실제 거리가 radius내에 있는지 검사하는 메서드입니다.
`UserLocationBasedMax` 클래스는 최대범위를 계산해서 들고있는 용도의 클래스로만 생각했어서 직접 거리계산까지 하는 책임을 갖는게 이상하다고 생각했습니다.

그런데 지금보니 이 클래스가 유틸 클래스라고 부를 수 있나에 의문이 드네요.😭

2022-09-14 06:09 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/common/util/DistanceCalcUtil.java
> +    }
맞습니다!
p3 -> 그런식으로 만들고 사용하는건 생각을 못했네요!

2022-09-14 06:11 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/store/controller/request/UserLocationInfoRequest.java
> +}
잘못된 값이 들어오면 아예 서비스까지 들어오기 전에 걸러내야한다고 생각해서 request에 검증로직을 넣었습니다!
근데 검증 로직을 request가 들고 있는것도 역할이 너무 과하게 주어진거 같아서 p3방식으로 변경하는게 더 좋을거 같네요.

2022-09-14 06:12 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
> +					radius))
DB에서 위치 기준 최대/최소 범위를 기준으로 가져온 데이터들이라서 실제로 거리를 계산하는 로직을 통해 한번 더 거르기 위함이었습니다.

2022-09-14 06:19 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
> +					radius))
DB에서 위치 기준 데이터를 걸렀는데 또 거르는 이유가 있나요?

2022-09-14 06:22 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/StoreService.java
> +					radius))
DB에서는 사각형 모양으로 범위를 잡고 조회하는데 원형으로 데이터를 주려면 가져온 데이터들을 돌면서 실제 거리를 검사한 뒤에 줘야한다고 생각했어요! (모서리 위치에 있는 데이터들은 걸러내야하는게 아닐까라는 생각에)

2022-09-14 06:23 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/store/service/dto/UserLocationBasedMaxRange.java
> +    private static final int EARTH_RADIUS = 3761;
주석으로 링크 추가해두겠습니다!

2022-09-14 08:11 UTC, jinan159 approved these changes
기나긴 PR 여정의 끝인가요
고생하셨습니다😁

2022-09-14 08:53 UTC, merged