[BE] 유저 카카오 로그인 API
jjik-muk/sikdorak pull request #42
Opened 2022-08-03 07:55 UTC by Seokho-Ham

### ❗️ 이슈 번호

<strong>
Closes #31 
</strong>

<br><br>

### 📝 구현 내용

- FeignClient를 사용한 카카오 api 사용 구현
- 카카오 로그인 기능 구현
  - 새로운 유저일 경우 저장 후 토큰 발급
  - 기존 유저일 경우 바로 토큰 발급
- 유저 통합 테스트 작성
- 유저 도메인 객체 및 테스트 작성

<br><br>

### 🙇🏻‍♂️ 리뷰어에게 부탁합니다!

현재 wiremock에 대한 학습이 부족해서 mock 테스트는 학습 후 진행하려고 합니다!
그래서 oauth 인수테스트에서 토큰을 발급하는 테스트는 현재 통과하지 못하는 상태입니다. 참고해주세요~

솔직담백한 리뷰 부탁드립니다~👍

2022-08-03 07:59 UTC, jinan159 commented on be/build.gradle
> +		epagesRestdocsVersion = '0.16.2'
`epagesRestdocsVersion = '0.16.2'` 이 부분은 이전에 swaggerUI 관련 라이브러리 관련 변수여서, 현재는 필요없으니 지우면 될 것 같습니다..!

```suggestion
```

2022-08-03 08:12 UTC, jinan159 commented on be/build.gradle
> +		epagesRestdocsVersion = '0.16.2'
`epagesRestdocsVersion = '0.16.2'` 이 부분은 이전에 swaggerUI 관련 라이브러리 관련 변수여서, 현재는 필요없으니 지우면 될 것 같습니다..!

```suggestion
```

2022-08-03 09:21 UTC, jinan159 commented on be/src/test/resources/application.yml
> +  refreshTokenExpiredMillisecond: 604800000
쿠킴이 디코에서 언급하신 부분이군요
`client_id` 와 `secretKey` 는 실제 운영용 정보와는 달라야할 것 같은데, 다른게 맞겠죠?

2022-08-03 09:32 UTC, jinan159 commented on be/src/test/java/com/jjikmuk/sikdorak/user/domain/EmailTest.java
> +            }
이 부분은 `@ValueSource` 로도 바꿀 수 있을 것 같네요!
(반영해도 좋고 넘어가도 좋습니다)

```suggestion
            @ParameterizedTest
            @ValueSource(strings = {
                    "s",
                    "name@mailcom",
                    "name#mail.com",
                    "name@mail",
                    "name@mail#.com",
                    " name@mail#.com",
                    "name@mail#.com ",
                    "name@ma-il#.com",
                    "name@mail.!com"})
            @DisplayName("예외를 반환한다.")
            void throw_Exception(String email) {
                assertThatThrownBy(() -> new Email(email))
                        .isInstanceOf(InvalidUserEmailException.class);
            }
```

2022-08-03 09:37 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/user/domain/User.java
> +    }
Embedded 객체를 풀어서 넘겨주는거 좋은 것 같습니다👍

2022-08-03 09:43 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/user/domain/User.java
> +import javax.persistence.*;
여러개를 참조하게되면서 IntelliJ 가 자동으로 wildcard imports 로 바꾼 것 같은데, 이 부분은 필요한 클래스만 참조하도록 변경하면 좋을 것 같습니다.
(소스코드상에서 와일드 카드를 single import 로 바꾸려면, 해당 라인에서 `option + enter` 를 하면 바꾸는 옵션이 나와요)

- [Disable wildcard imports](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports)

2022-08-03 09:46 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/user/domain/Nickname.java
> +    }
`boolean` 을 반환하는 메소드는 `is~` 이런 네이밍이 들어가면 좋을 것 같습니다!

2022-08-03 09:46 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/user/domain/Email.java
> +    }
https://github.com/jjik-muk/sikdorak/pull/42/files#r936462399
여기와 같은 의견입니다.

2022-08-03 10:25 UTC, Seokho-Ham commented on be/build.gradle
> +		epagesRestdocsVersion = '0.16.2'
리베이스 과정에서 놓쳤나보네요! 지워버리겠습니다!

2022-08-03 10:29 UTC, Seokho-Ham commented on be/src/test/resources/application.yml
> +  refreshTokenExpiredMillisecond: 604800000
넵 일단 이건 테스트에서 사용하려고 넣어둔것이고 `secret_key`는 서브모듈에서 다르게 설정하려고 합니다!
근데 혹시 `client_id`는 왜 달라야 할까요? 저기서 `client_id`는카카오 api를 사용하려고 저희 앱을 등록한것에 대한 id값입니다!

2022-08-03 10:31 UTC, jinan159 commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/OAuthController.java
> +    }
여기서 `AccessToken` 과 `RefreshToken` 을 둘다 `ResponseBody` 로 보내주고 있는데, 
`RefreshToken` 은 탈취되는것을 예방하기 위해 조금 더 보안을 신경써서 보내야할 것 같다는 생각이 들어요..!

저도 잘 몰라서 알아보니, httponly secure cookie 로 보내는 경우가 많은 것 같네요.
다른분들 의견도 궁금합니다.

참고한 링크
- https://dncjf64.tistory.com/292
- https://theheydaze.tistory.com/550

2022-08-03 10:33 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/user/domain/Nickname.java
> +    }
생각해보니 `isValidXX` 같은 형식의 네이밍이 더 의미적으로 명확해질 것 같네요! 반영하겠습니다~

2022-08-03 10:33 UTC, jinan159 commented on be/src/test/resources/application.yml
> +  refreshTokenExpiredMillisecond: 604800000
아 `client_id` 는 제가 착각한 것 같습니다!😅
`client_id` 는 노출되도 상관없는게 맞는 것 같아요 ㅎㅎ

2022-08-03 10:45 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/OAuthController.java
> +    }
넵 저도 말씀하신 의견에 대해서 동의해요!
근데 제가 알기로는 프론트에서 httponly secure cookie에 접근하려면 https를 사용해야하는것으로 알고 있습니다. 당장은 저희가 https를 사용하지 않아서 일단 body로 내려주고 있습니다!

2022-08-03 10:47 UTC, Seokho-Ham commented
p.s) 현재 pr에 올라간 application.yml에 설정된 값들을 추후 submodule에 위치한 설정파일에도 추가하려고 하는데 혹시나 삭제 or 추가해야된다고 생각되는 부분들은 말씀해주세요!

2022-08-03 14:47 UTC, ku-kim commented on be/build.gradle
> +		epagesRestdocsVersion = '0.16.2'
good

2022-08-03 14:48 UTC, ku-kim commented on be/src/test/resources/application.yml
> +  refreshTokenExpiredMillisecond: 604800000
해당 부분은 추후에 git submodules의 application-test로 변경해야겠군요

2022-08-03 15:03 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +package com.jjikmuk.sikdorak.auth.controller.dto.response;
review 패키지 구조와 동일하면 좋을거같아요.

/auth/controller/dto/response/ -> /auth/controller/response/

dto 패키지 구조가 없어요!

2022-08-03 15:03 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +@ToString
ToString은 다른곳에서 사용되고있나요?

2022-08-03 15:48 UTC, ku-kim requested changes

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +}
```suggestion

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Getter;
import lombok.ToString;

@Getter
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class OAuthTokenResponse {

    private String tokenType;

    private String accessToken;

    private int expiresIn;

    private String refreshToken;

    private int refreshTokenExpiresIn;
}
```

`@JsonProperty` 사용이 스네이크 케이스라면 JsonNaming 을 사용해 한 번에 코드를 줄일 수 있어요

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/auth/domain/JwtProvider.java
> +        }
token이 에러인 경우 아직 조치가 없는건가요?

추후에 로직이 추가된다면 해당 if 조건문이 메서드 제일 위에 있는게 좋아보여요!

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/FeignClientHeaderConfiguration.java
> +}
```suggestion
import feign.RequestInterceptor;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

public class FeignClientHeaderConfiguration {

    public static final String APPLICATION_FORM_URLENCODED_UTF8_VALUE =
        MediaType.APPLICATION_FORM_URLENCODED_VALUE + ";charset=utf-8";

    @Bean
    public RequestInterceptor requestInterceptor() {
        return requestTemplate -> requestTemplate.header(HttpHeaders.CONTENT_TYPE, APPLICATION_FORM_URLENCODED_UTF8_VALUE);
    }

}
```

상수는 어떠세요?

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/KakaoAccountResponseDeserializer.java
> +}
JsonDeserializer가 필요한 이유가 있었나요?

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/common/properties/KakaoProperties.java
> +}
프로퍼티들 생성자 주입할 때`@Validated` 를 사용하여 유효성체크 할 수 있어요

예를 들어

```java
@Getter
@Validated
@ConfigurationProperties("oauth.github")
@ConstructorBinding
public class GithubProperty {

	@NotEmpty
	private final String accessTokenUri;

	@NotEmpty
	private final String userInfoUri;

	@NotEmpty
	private final String clientId;

	@NotEmpty
	private final String clientSecret;

	public GithubProperty(String accessTokenUri, String userInfoUri, String clientId,
		String clientSecret) {
		this.accessTokenUri = accessTokenUri;
		this.userInfoUri = userInfoUri;
		this.clientId = clientId;
		this.clientSecret = clientSecret;
	}
}

```

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +@Service
코드보면서 생각났는데 어노테이션 순서를 통일해야겠군요.!

2022-08-03 15:48 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +
테스트 클래스 최상단에
`@DisplayName("ReviewInsert 통합테스트")` 와 같은 설명이 있었으면 좋을거같아요!

이전에 구현한 코드(ReviewAcceptanceTest) 제외하고 다른 테스트 모두 클래스명 위에 `DisplayName()`이 추가되어있어요!

2022-08-03 15:48 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +}
동일한 id의 유저 중복 등록에 대한 테스트가 필요해보여요!

2022-08-03 15:48 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +    }
유저 생성 로직에 
해당 유저가 존재하는지 유효성 검증 필요하지 않을까요?

다만  OAuthService에서만 UserService.createUser() 를 사용하고 있고 OAuthService에서 이미 유저에 대한 유효성 검증을 하고 있어 코드가 중복되는거 같지만.. 고민이네요!
어떻게 생각하시나요?

2022-08-03 15:52 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +    @Autowired
테스트 클래스 최상단에 테스트 설명이 있으면 좋을거같아요!

```suggestion
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("UserCreate 통합테스트")
public class UserCreateIntegrationTest extends InitIntegrationTest {

    @Autowired
```

2022-08-03 15:52 UTC, Seokho-Ham commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +}
해당 부분은 원래 중복 등록에 대한 검증 테스트를 작성했었습니다!

소셜 로그인 시 카카오에서 제공하는 id를 기준으로 유저 존재 여부를 확인하는데, 이미 가입한 적이 있는 유저가 로그인을 할 경우 예외를 던지는게 아닌 로그인이 성공해야되겠다고 생각이 되더라구요.

카카오에서 발급하는 id값은 회원번호이기 때문에 중복될 수 없다고 판단되었고, 그래서 중복 등록에 대한 테스트는 제거했습니다!

2022-08-03 15:54 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +    }
이 부분도 위에서 말씀드렸던것처럼,  카카오의 회원번호를 기준으로 검사하기 때문에 중복이 발생할 수 없다고 생각되었습니다.
그래서 OAuthService에서 기존에 존재하는 유저일 경우, 저장없이 바로 토큰을 발급해주는 방식으로 구현되어 있습니다!

2022-08-03 15:54 UTC, seokho-ham commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +@Service
안그래도 말씀드리고 싶었던 부분인데!! 내일 한번 이야기해보죠!

2022-08-03 15:55 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/common/properties/KakaoProperties.java
> +}
이건 몰랐네요😭 반영하겠습니다!

2022-08-03 15:57 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/common/config/feignclient/KakaoAccountResponseDeserializer.java
> +}
해당 json response를 처리하려면 dto안에  dto안에 dto형태로 계속해서 감싸는 용도의 dto를 만들어야하더라구요.
그 작업이 번거롭기도하고, 실제 값에 접근할때도 계속 getter를 사용해서 접근하는것보다는 애초에 역직렬화 과정에서 한번에 원하는 형태의 dto로 만들고 싶어서 사용했습니다.

2022-08-03 15:59 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/auth/domain/JwtProvider.java
> +        }
해당 로직은 인터셉터와 토큰 재발급 api만들때 수정할 계획입니다!

2022-08-03 16:00 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +}
저 방법이 훨씬 깔끔하겠네요! 또 하나 알아갑니다ㅎㅎ 반영할게요~

2022-08-03 16:00 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +@ToString
미처 지우지 못했네요;;

2022-08-03 16:01 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +package com.jjikmuk.sikdorak.auth.controller.dto.response;
이것도 제가 제대로 확인을 못했네요! 수정할게요~

2022-08-03 16:01 UTC, Seokho-Ham commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +    @Autowired
👍👍👍

2022-08-03 16:03 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +    }
그렇군요.!
제가 말씀드린 부분은  UserService 가 접근 제어자가 public이라 다른 곳에서도 사용할 수 있어 보여서요.!

2022-08-03 16:05 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +    }
UserService 역할이 OAuthService에 완전 종속적이라면 패키지 구조로 제한을 두거나
UserService 로직이 OAuthService 안에 들어가있어도 괜찮다 생각이 들었어요.

UserService 로직이 완전 다른 패키지로 구분되어있다면 어디서든 사용할 수 있는거라고 생각해
해당 로직에 대한 검증이 들어가야한다고 생각했습니다

2022-08-03 16:06 UTC, ku-kim commented on be/src/main/java/com/jjikmuk/sikdorak/auth/controller/dto/response/OAuthTokenResponse.java
> +}
suggestion commit을 사용해보는것도 ㅎㅎ

2022-08-03 16:12 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +    @Autowired
단위테스트에도 마찬가지였어유 ㅜ 🙇‍♂️

2022-08-03 16:17 UTC, Seokho-Ham commented on be/src/main/java/com/jjikmuk/sikdorak/user/service/UserService.java
> +    }
처음에 구현할때는 유저 서비스에서 유저를 생성하는 작업 자체가 로그인하는 경우가 아니라면 사용할일이 없겠지라고 생각하고 짰는데 .. 검증도 없는 public 이었다니;;

OAuthService에 들어가기보다는 해당 메서드에 검증 로직을 넣어서 중복일 경우 예외를 던지도록 하고, 테스트도 추가하는게 맞을것 같네요!
지웠던 검증로직과 테스트를 되살려야겠습니다!

2022-08-04 06:30 UTC, ku-kim approved these changes

2022-08-04 06:30 UTC, ku-kim commented on be/src/test/java/com/jjikmuk/sikdorak/integration/user/UserCreateIntegrationTest.java
> +    }
Good!

2022-08-04 06:31 UTC, merged